==================================================================================================== test session starts =====================================================================================================
platform linux -- Python 3.6.8, pytest-7.0.0, pluggy-1.0.0 -- /home/opc/REPOS/fireup/test/venv/bin/python3
cachedir: .pytest_cache
rootdir: /home/opc/REPOS/fireup/test
collecting ... collected 61 items

opsefficiency/test_suite_4_1.py::test_review_point PASSED                                                                                                                                                              [  1%]
opsefficiency/test_suite_4_2.py::test_review_point PASSED                                                                                                                                                              [  3%]
opsefficiency/test_suite_4_3.py::test_review_point PASSED                                                                                                                                                              [  4%]
opsefficiency/test_suite_4_4.py::test_review_point PASSED                                                                                                                                                              [  6%]
opsefficiency/test_suite_4_5.py::test_review_point PASSED                                                                                                                                                              [  8%]
opsefficiency/test_suite_4_6.py::test_review_point PASSED                                                                                                                                                              [  9%]
opsefficiency/test_suite_4_7.py::test_review_point FAILED                                                                                                                                                              [ 11%]
performancecost/test_suite_3_1.py::test_review_point PASSED                                                                                                                                                            [ 13%]
performancecost/test_suite_3_10.py::test_review_point PASSED                                                                                                                                                           [ 14%]
performancecost/test_suite_3_11.py::test_review_point PASSED                                                                                                                                                           [ 16%]
performancecost/test_suite_3_2.py::test_review_point PASSED                                                                                                                                                            [ 18%]
performancecost/test_suite_3_3.py::test_review_point PASSED                                                                                                                                                            [ 19%]
performancecost/test_suite_3_4.py::test_review_point PASSED                                                                                                                                                            [ 21%]
performancecost/test_suite_3_5.py::test_review_point PASSED                                                                                                                                                            [ 22%]
performancecost/test_suite_3_6.py::test_review_point PASSED                                                                                                                                                            [ 24%]
performancecost/test_suite_3_7.py::test_review_point PASSED                                                                                                                                                            [ 26%]
performancecost/test_suite_3_8.py::test_review_point PASSED                                                                                                                                                            [ 27%]
performancecost/test_suite_3_9.py::test_review_point PASSED                                                                                                                                                            [ 29%]
reliabilityresilience/test_suite_2_1.py::test_review_point FAILED                                                                                                                                                      [ 31%]
reliabilityresilience/test_suite_2_10.py::test_review_point PASSED                                                                                                                                                     [ 32%]
reliabilityresilience/test_suite_2_11.py::test_review_point PASSED                                                                                                                                                     [ 34%]
reliabilityresilience/test_suite_2_12.py::test_review_point PASSED                                                                                                                                                     [ 36%]
reliabilityresilience/test_suite_2_13.py::test_review_point PASSED                                                                                                                                                     [ 37%]
reliabilityresilience/test_suite_2_14.py::test_review_point FAILED                                                                                                                                                     [ 39%]
reliabilityresilience/test_suite_2_15.py::test_review_point PASSED                                                                                                                                                     [ 40%]
reliabilityresilience/test_suite_2_16.py::test_review_point PASSED                                                                                                                                                     [ 42%]
reliabilityresilience/test_suite_2_17.py::test_review_point FAILED                                                                                                                                                     [ 44%]
reliabilityresilience/test_suite_2_2.py::test_review_point PASSED                                                                                                                                                      [ 45%]
reliabilityresilience/test_suite_2_3.py::test_review_point PASSED                                                                                                                                                      [ 47%]
reliabilityresilience/test_suite_2_4.py::test_review_point PASSED                                                                                                                                                      [ 49%]
reliabilityresilience/test_suite_2_5.py::test_review_point PASSED                                                                                                                                                      [ 50%]
reliabilityresilience/test_suite_2_6.py::test_review_point FAILED                                                                                                                                                      [ 52%]
reliabilityresilience/test_suite_2_7.py::test_review_point PASSED                                                                                                                                                      [ 54%]
reliabilityresilience/test_suite_2_8.py::test_review_point PASSED                                                                                                                                                      [ 55%]
reliabilityresilience/test_suite_2_9.py::test_review_point PASSED                                                                                                                                                      [ 57%]
securitycompliance/test_suite_1_1.py::test_review_point PASSED                                                                                                                                                         [ 59%]
securitycompliance/test_suite_1_10.py::test_review_point PASSED                                                                                                                                                        [ 60%]
securitycompliance/test_suite_1_11.py::test_review_point PASSED                                                                                                                                                        [ 62%]
securitycompliance/test_suite_1_12.py::test_review_point PASSED                                                                                                                                                        [ 63%]
securitycompliance/test_suite_1_13.py::test_review_point PASSED                                                                                                                                                        [ 65%]
securitycompliance/test_suite_1_14.py::test_review_point PASSED                                                                                                                                                        [ 67%]
securitycompliance/test_suite_1_15.py::test_review_point PASSED                                                                                                                                                        [ 68%]
securitycompliance/test_suite_1_16.py::test_review_point PASSED                                                                                                                                                        [ 70%]
securitycompliance/test_suite_1_17.py::test_review_point PASSED                                                                                                                                                        [ 72%]
securitycompliance/test_suite_1_18.py::test_review_point PASSED                                                                                                                                                        [ 73%]
securitycompliance/test_suite_1_19.py::test_review_point PASSED                                                                                                                                                        [ 75%]
securitycompliance/test_suite_1_2.py::test_review_point PASSED                                                                                                                                                         [ 77%]
securitycompliance/test_suite_1_20.py::test_review_point PASSED                                                                                                                                                        [ 78%]
securitycompliance/test_suite_1_21.py::test_review_point PASSED                                                                                                                                                        [ 80%]
securitycompliance/test_suite_1_22.py::test_review_point PASSED                                                                                                                                                        [ 81%]
securitycompliance/test_suite_1_23.py::test_review_point PASSED                                                                                                                                                        [ 83%]
securitycompliance/test_suite_1_24.py::test_review_point PASSED                                                                                                                                                        [ 85%]
securitycompliance/test_suite_1_25.py::test_review_point PASSED                                                                                                                                                        [ 86%]
securitycompliance/test_suite_1_26.py::test_review_point PASSED                                                                                                                                                        [ 88%]
securitycompliance/test_suite_1_3.py::test_review_point PASSED                                                                                                                                                         [ 90%]
securitycompliance/test_suite_1_4.py::test_review_point PASSED                                                                                                                                                         [ 91%]
securitycompliance/test_suite_1_5.py::test_review_point PASSED                                                                                                                                                         [ 93%]
securitycompliance/test_suite_1_6.py::test_review_point PASSED                                                                                                                                                         [ 95%]
securitycompliance/test_suite_1_7.py::test_review_point PASSED                                                                                                                                                         [ 96%]
securitycompliance/test_suite_1_8.py::test_review_point PASSED                                                                                                                                                         [ 98%]
securitycompliance/test_suite_1_9.py::test_review_point PASSED                                                                                                                                                         [100%]

========================================================================================================== FAILURES ==========================================================================================================
_____________________________________________________________________________________________________ test_review_point ______________________________________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7fb8ec73b0b8>

    def test_review_point(capsys):
    
        result_dictionary = PatchesAndUpdates(Statics.__rp_4_7['entry'],
        Statics.__rp_4_7['area'],
        Statics.__rp_4_7['sub_area'],
        Statics.__rp_4_7['review_point'],
        True, [], [], [], [],
        get_config_and_signer()[0],
        get_config_and_signer()[1]
        )
    
        results_in_fault=0
        dictionary = result_dictionary.analyze_entity(Statics.__rp_4_7['entry'])
    
        for item in dictionary[Statics.__rp_4_7['entry']]['findings']:
            debug(item)
            results_in_fault += 1
    
>       assert results_in_fault == 137
E       assert 138 == 137
E         +138
E         -137

opsefficiency/test_suite_4_7.py:38: AssertionError
_____________________________________________________________________________________________________ test_review_point ______________________________________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7fb8e588e7f0>

    def test_review_point(capsys):
    
        result_dictionary = CheckAutoscaling(Statics.__rp_2_1['entry'],
        Statics.__rp_2_1['area'],
        Statics.__rp_2_1['sub_area'],
        Statics.__rp_2_1['review_point'],
        True, [], [], [], [],
        get_config_and_signer()[0],
        get_config_and_signer()[1]
        )
    
        results_in_fault=0
        dictionary = result_dictionary.analyze_entity(Statics.__rp_2_1['entry'])
    
        for item in dictionary[Statics.__rp_2_1['entry']]['findings']:
            debug(item)
            results_in_fault += 1
    
    
>       assert results_in_fault == 10
E       assert 8 == 10
E         +8
E         -10

reliabilityresilience/test_suite_2_1.py:40: AssertionError
_____________________________________________________________________________________________________ test_review_point ______________________________________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7fb8c55e4b38>

    def test_review_point(capsys):
    
        result_dictionary = CheckBackupPolicies(Statics.__rp_2_14['entry'],
        Statics.__rp_2_14['area'],
        Statics.__rp_2_14['sub_area'],
        Statics.__rp_2_14['review_point'],
        True, [], [], [], [],
        get_config_and_signer()[0],
        get_config_and_signer()[1]
        )
    
        results_in_fault=0
        dictionary = result_dictionary.analyze_entity(Statics.__rp_2_14['entry'])
    
        for item in dictionary[Statics.__rp_2_14['entry']]['findings']:
            debug(item)
            results_in_fault += 1
    
    
>       assert results_in_fault == 140
E       assert 141 == 140
E         +141
E         -140

reliabilityresilience/test_suite_2_14.py:39: AssertionError
----------------------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------------------
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: filestorage.us-phoenix-1.oraclecloud.com
_____________________________________________________________________________________________________ test_review_point ______________________________________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7fb7a463c0f0>

    def test_review_point(capsys):
    
        result_dictionary = ReplicateData(Statics.__rp_2_17['entry'],
        Statics.__rp_2_17['area'],
        Statics.__rp_2_17['sub_area'],
        Statics.__rp_2_17['review_point'],
        True, [], [], [], [],
        get_config_and_signer()[0],
        get_config_and_signer()[1]
        )
    
        results_in_fault=0
        dictionary = result_dictionary.analyze_entity(Statics.__rp_2_17['entry'])
    
        for item in dictionary[Statics.__rp_2_17['entry']]['findings']:
            debug(item)
            results_in_fault += 1
    
>       assert results_in_fault == 251
E       assert 252 == 251
E         +252
E         -251

reliabilityresilience/test_suite_2_17.py:38: AssertionError
----------------------------------------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------------------------------------
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.eu-frankfurt-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.uk-london-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-ashburn-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
WARNING  oci._vendor.urllib3.connectionpool:connectionpool.py:309 Connection pool is full, discarding connection: iaas.us-phoenix-1.oraclecloud.com
_____________________________________________________________________________________________________ test_review_point ______________________________________________________________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x7fb928c0add8>

    def test_review_point(capsys):
    
        result_dictionary = LowLimits(Statics.__rp_2_6['entry'],
        Statics.__rp_2_6['area'],
        Statics.__rp_2_6['sub_area'],
        Statics.__rp_2_6['review_point'],
        True, [], [], [], [],
        get_config_and_signer()[0],
        get_config_and_signer()[1]
        )
    
        results_in_fault=0
        dictionary = result_dictionary.analyze_entity(Statics.__rp_2_6['entry'])
    
        for item in dictionary[Statics.__rp_2_6['entry']]['findings']:
            debug(item)
            results_in_fault += 1
    
    
>       assert results_in_fault == 4959
E       assert 4958 == 4959
E         +4958
E         -4959

reliabilityresilience/test_suite_2_6.py:40: AssertionError
===================================================================================================== slowest durations ======================================================================================================
273.42s call     opsefficiency/test_suite_4_7.py::test_review_point
94.91s call     opsefficiency/test_suite_4_3.py::test_review_point
80.62s call     performancecost/test_suite_3_6.py::test_review_point
57.63s call     opsefficiency/test_suite_4_1.py::test_review_point
53.27s call     securitycompliance/test_suite_1_18.py::test_review_point
48.13s call     reliabilityresilience/test_suite_2_14.py::test_review_point
43.55s call     opsefficiency/test_suite_4_4.py::test_review_point
31.78s call     reliabilityresilience/test_suite_2_4.py::test_review_point
31.21s call     reliabilityresilience/test_suite_2_17.py::test_review_point
29.05s call     reliabilityresilience/test_suite_2_11.py::test_review_point
27.59s call     performancecost/test_suite_3_10.py::test_review_point
25.47s call     reliabilityresilience/test_suite_2_1.py::test_review_point
23.49s call     performancecost/test_suite_3_4.py::test_review_point
23.45s call     reliabilityresilience/test_suite_2_2.py::test_review_point
18.74s call     reliabilityresilience/test_suite_2_12.py::test_review_point
16.95s call     opsefficiency/test_suite_4_6.py::test_review_point
16.01s call     reliabilityresilience/test_suite_2_7.py::test_review_point
15.85s call     reliabilityresilience/test_suite_2_15.py::test_review_point
13.70s call     performancecost/test_suite_3_5.py::test_review_point
13.26s call     securitycompliance/test_suite_1_10.py::test_review_point
12.94s call     securitycompliance/test_suite_1_26.py::test_review_point
9.70s call     performancecost/test_suite_3_2.py::test_review_point
7.61s call     securitycompliance/test_suite_1_11.py::test_review_point
4.37s call     reliabilityresilience/test_suite_2_13.py::test_review_point
3.46s call     securitycompliance/test_suite_1_19.py::test_review_point
3.32s call     securitycompliance/test_suite_1_6.py::test_review_point
2.82s call     performancecost/test_suite_3_9.py::test_review_point
2.64s call     securitycompliance/test_suite_1_12.py::test_review_point
2.33s call     performancecost/test_suite_3_1.py::test_review_point
2.17s call     reliabilityresilience/test_suite_2_5.py::test_review_point
1.95s call     performancecost/test_suite_3_7.py::test_review_point
1.94s call     securitycompliance/test_suite_1_24.py::test_review_point
1.83s call     opsefficiency/test_suite_4_5.py::test_review_point
1.80s call     performancecost/test_suite_3_11.py::test_review_point
1.69s call     performancecost/test_suite_3_8.py::test_review_point
1.66s call     opsefficiency/test_suite_4_2.py::test_review_point
1.34s call     securitycompliance/test_suite_1_1.py::test_review_point
1.10s call     securitycompliance/test_suite_1_15.py::test_review_point
1.09s call     reliabilityresilience/test_suite_2_10.py::test_review_point
1.07s call     reliabilityresilience/test_suite_2_8.py::test_review_point
1.03s call     securitycompliance/test_suite_1_21.py::test_review_point
1.03s call     securitycompliance/test_suite_1_7.py::test_review_point
0.99s call     securitycompliance/test_suite_1_13.py::test_review_point
0.93s call     performancecost/test_suite_3_3.py::test_review_point
0.86s call     securitycompliance/test_suite_1_8.py::test_review_point
0.82s call     securitycompliance/test_suite_1_9.py::test_review_point
0.80s call     reliabilityresilience/test_suite_2_3.py::test_review_point
0.80s call     securitycompliance/test_suite_1_20.py::test_review_point
0.79s call     reliabilityresilience/test_suite_2_9.py::test_review_point
0.78s call     securitycompliance/test_suite_1_22.py::test_review_point
0.77s call     securitycompliance/test_suite_1_16.py::test_review_point
0.71s call     reliabilityresilience/test_suite_2_6.py::test_review_point
0.71s call     securitycompliance/test_suite_1_14.py::test_review_point
0.70s call     securitycompliance/test_suite_1_17.py::test_review_point
0.70s call     reliabilityresilience/test_suite_2_16.py::test_review_point
0.67s call     securitycompliance/test_suite_1_23.py::test_review_point
0.64s call     securitycompliance/test_suite_1_4.py::test_review_point
0.53s call     securitycompliance/test_suite_1_3.py::test_review_point
0.50s call     securitycompliance/test_suite_1_2.py::test_review_point
0.21s call     securitycompliance/test_suite_1_5.py::test_review_point
0.13s call     securitycompliance/test_suite_1_25.py::test_review_point

(122 durations < 0.005s hidden.  Use -vv to show these durations.)
================================================================================================== short test summary info ===================================================================================================
FAILED opsefficiency/test_suite_4_7.py::test_review_point - assert 138 == 137
FAILED reliabilityresilience/test_suite_2_1.py::test_review_point - assert 8 == 10
FAILED reliabilityresilience/test_suite_2_14.py::test_review_point - assert 141 == 140
FAILED reliabilityresilience/test_suite_2_17.py::test_review_point - assert 252 == 251
FAILED reliabilityresilience/test_suite_2_6.py::test_review_point - assert 4958 == 4959
========================================================================================= 5 failed, 56 passed in 1022.89s (0:17:02) ==========================================================================================
